export const FAVORITES_GET_FAVORITES_FROM_COOKIE =
  "FAVORITES_GET_FAVORITES_FROM_COOKIE";
export const FAVORITES_GET_FAVORITE_PRODUCTS =
  "FAVORITES_GET_FAVORITE_PRODUCTS";
export const FAVORITES_TOGGLE_FAVORITE = "FAVORITES_TOGGLE_FAVORITE";

export const PRODUCT_SET_PRODUCT = "PRODUCT_SET_PRODUCT";
export const PRODUCT_SET_PROPERTY_GROUPS = "PRODUCT_SET_PROPERTY_GROUPS";
export const PRODUCT_GET_RELATED_PRODUCTS = "PRODUCT_GET_RELATED_PRODUCTS";
export const PRODUCT_SET_AVAILABLE_PRODUCT_LABELS =
  "PRODUCT_SET_AVAILABLE_PRODUCT_LABELS";
export const PRODUCT_SET_PARAMS = "PRODUCT_SET_PARAMS";

export const COLLECTIONS_GET_COLLECTION = "COLLECTIONS_GET_COLLECTION";
export const COLLECTIONS_SET_COLLECTIONS = "COLLECTIONS_SET_COLLECTIONS";
export const COLLECTIONS_SET_PAGINATION = "COLLECTIONS_SET_PAGINATION";
export const COLLECTIONS_SET_FILTERS = "COLLECTIONS_SET_FILTERS";
export const COLLECTIONS_SET_PRODUCTS = "COLLECTIONS_SET_PRODUCTS";
export const COLLECTIONS_SET_SELECTED_FILTER =
  "COLLECTIONS_SET_SELECTED_FILTER";
export const COLLECTIONS_SET_CHANGED_FILTERS =
  "COLLECTIONS_SET_CHANGED_FILTERS";
export const COLLECTIONS_CLEAR_CHANGED_FILTERS =
  "COLLECTIONS_CLEAR_CHANGED_FILTERS";
export const COLLECTIONS_CLEAR_FILTER = "COLLECTIONS_CLEAR_FILTER";
export const COLLECTIONS_CLEAR_ALL_FILTERS = "COLLECTIONS_CLEAR_ALL_FILTERS";
export const COLLECTIONS_TOGGLE_MOBILE_FILTER =
  "COLLECTIONS_TOGGLE_MOBILE_FILTER";
export const COLLECTIONS_TOGGLE_MOBILE_COLLECTIONS =
  "COLLECTIONS_TOGGLE_MOBILE_COLLECTIONS";
export const COLLECTIONS_SET_LOADING = "COLLECTIONS_SET_LOADING";
export const COLLECTIONS_SET_INTERFACE_SETTINGS =
  "COLLECTIONS_SET_INTERFACE_SETTINGS";
